### ISSUE TITLE
Environment key "owin.TraceOutput"

### ISSUE THREAD

**Issue by loudej** [owin/owin.dll#11]
Based on Rack's "rack.output" key - this would be a host-provided TextWriter that logging output could be directed onto.

This enabled a developer of an owin web site to have a consistent and host-agnostic place to direct runtime or diagnostic information.

For console application hosting this would map directly onto stdout. For aspnet this could be directed any number of places. Trace.WriteLine for example? If a company is providing shared web hosting is OWIN-aware, they may introduce their own TextWriter object for trace output, which could direct logging output into a system the client could access via control panel or other means.

**Comment by Tratcher** [comment]
See host.TraceOutput.
