### ISSUE TITLE
Contributor agreement sender missing

### ISSUE THREAD

**Issue by gsscoder** [owin/owin.dll#18]
I've printed, completed an signed the contributor agreement.

Please provide an address to send PDF.

Regards,
Giacomo Stelluti Scala

**Comment by serialseb** [comment]
What is the status on this?

**Comment by panesofglass** [comment]
I believe these used to go to @loudej but should probably now go to @dragan since the project is sponsored by Monkey Square.

**Comment by damianh** [comment]
What is the contributor agreement for? Do I need to sign one? Since there is no code, is it necessary?
