### ISSUE TITLE
Use github issues for voting on proposals

### ISSUE THREAD

**Issue by damianh** [owin/owin.dll#22]
Create a label called 'proposal' for initial.. proposals. When enough discussion / lamenting / gnashing of teeth has occurred, the management committee can move the issue to vote stage by using the vote label if appropriate. We also should leverage milestones feature to associated proposals with versions of the spec.

**Comment by panesofglass** [comment]
:+1: though we should use [owin.github.com](https://github.com/owin/owin.github.com).

**Comment by damianh** [comment]
Sir yes sir!

**Comment by skoon** [comment]
Agreed

**Comment by serialseb** [comment]
:+1:

**Comment by serialseb** [comment]
Should someone on the committee add the label and the milestones for 1.1 (MidFunc) and maybe 1.2 (BuildFunc)?

**Comment by panesofglass** [comment]
I think the idea is that we move away from having any code altogether unless they are samples. Should I push that for a vote?

**Comment by panesofglass** [comment]
I'm going to close this and add the milestones @serialseb suggested to the owin.github.com project.

**Comment by panesofglass** [comment]
[Milestones created](https://github.com/owin/owin.github.com/issues/milestones?with_issues=no)
