### ISSUE TITLE
server.User common key

### ISSUE THREAD

**Issue by damianh** [owin/owin.dll#23]
I'm just going to make this statement for discussion purposes and does not imply I agree with it :)

`server.User` which is a `ClaimsPrincipal` has become the defacto standard key for identifying a user in a request pipeline. It should be at least added commmon keys.

**Comment by panesofglass** [comment]
I am for this idea. 

-----Original Message-----

**Comment by khellang** [comment]
:+1:

**Comment by Tratcher** [comment]
IPrincipal was more generally applicable than ClaimsPrincipal, especially since ClaimsPrincipal isn't available on .NET 4.0 (except as a not-quite-matching external library).

**Comment by damianh** [comment]
That's another question, are we sticking on .net 4 as our base target
framework, what with xp's demise and the other thing that's happening?

Inb4 grumpydev and his win98 users.

**Comment by Tratcher** [comment]
ClaimsPrincipal implements IPrincipal, so they aren't mutually exclusive.  We could set IPrincipal as the minimum and recommend ClaimsPrincipal where available.

Katana v3 completely removes .NET 4.0 support, but that is primarily for engineering reasons (complexity, perf, etc.).

**Comment by damianh** [comment]
Is anyone or anything actually using IPrincipal in a owin based app? Even when using the NTLM auth in a self-host, server.User is still a ClaimsPrincipal.

**Comment by Tratcher** [comment]
For WindowsAuth it's a WindowsPrincipal.  In 4.0 it had no base class, just IPrincipal. In 4.5 they added the ClaimsPrincipal base class.
http://msdn.microsoft.com/en-us/library/system.security.principal.windowsprincipal(v=vs.100).aspx

**Comment by serialseb** [comment]
What is the state for existing custom forms auth on existing asp.net with owin components working in parallel? Is the asp.net <-> owin adapter out there supporting translating from whatever asp.net supports to ClaimsPrincipal? Should it?

Which of the supported hosts and consumers rely on this key being a ClaimsPrincipal? How many are 4.5 only?

**Comment by Tratcher** [comment]
Nothing in Katana requires it to be a ClaimsPrincipal, though we do use that extensively.  If we need a ClaimsPrincipal and don't get one, then we wrap it with the built in constructor.

We haven't made much effort to interop with the built in ASP.NET forms auth. We built our own in the cookie auth middleware because we wanted more configurability.

I can't speak for consuming apps and frameworks...

**Comment by serialseb** [comment]
So would it be the host job to turn any IPrincipal into a ClaimsPrincipal? Would people have to implement anything more than a wrapper around the current principal on the current host context?

Running katana on top of existing .net is going to be the reality for most long-running projects I'm working on for big clients, so compatibility (not preventing any current scenario) and ease of migration (writing your own middleware easily to wrap your existing IPrincipal implementation, or any asp.net one for that matter) is of the uttermost importance to me.

**Comment by damianh** [comment]
Moved to https://github.com/owin/owin.github.com/issues/9 . Please continue discussion there.
